force-app/main/default/objects/Employee__c/fields/Total_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Total_Leaves__c</fullName>
    <label>Total Leaves</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Used_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Used_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Leaves</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Request  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Requests</relationshipLabel>
    <relationshipName>Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeaveRequestServiceTest.cls
@isTest
public class LeaveRequestServiceTest {

    @isTest
    static void testUpdateLeaveBalance() {

        Employee__c emp = new Employee__c(
            Name = 'Test Employee',
            Total_Leaves__c = 20,
            Used_Leaves__c = 0
        );
        insert emp;

        Leave_Request__c leaveRequest = new Leave_Request__c(
            Employee__c = emp.Id,
            Start_Date__c = Date.today(),
            End_Date__c = Date.today().addDays(2),
            Status__c = 'Approved'
        );

        insert leaveRequest;

        Employee__c updatedEmp = [
            SELECT Used_Leaves__c
            FROM Employee__c
            WHERE Id = :emp.Id
        ];

        System.assertEquals(3, updatedEmp.Used_Leaves__c);
    }
}