force-app/main/default/objects/Employee__c/fields/Used_Leaves__c.field-meta.xml
<CustomField>
    <fullName>Used_Leaves__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Used Leaves</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Request  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Leave Requests</relationshipLabel>
    <relationshipName>Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Total_Leave_Days__c.field-meta.xml
<CustomField>
    <fullName>Total_Leave_Days__c</fullName>
    <formula>End_Date__c - Start_Date__c + 1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Leave Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeaveRequestService.cls
public with sharing class LeaveRequestService {

    public static void updateLeaveBalance(List<Leave_Request__c> leaveRequests) {

        for (Leave_Request__c leaveRequest : leaveRequests) {

            if (leaveRequest.Status__c == 'Approved') {

                Employee__c employee = [
                    SELECT Id, Used_Leaves__c
                    FROM Employee__c
                    WHERE Id = :leaveRequest.Employee__c
                ];

                employee.Used_Leaves__c =
                    employee.Used_Leaves__c + leaveRequest.Total_Leave_Days__c;

                update employee;
            }
        }
    }
}